import { url } from "inspector";
import Navigation from "./components/navigation";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className="bg-gradient-to-b from-slate-950 from-60% to-indigo-950"
        // style={{ 
        //   backgroundImage: `url("images/bokeh.jpg")`
        // }}
      >
        <Navigation />
        <div className="container mx-auto px-4">
        <div className="w-full h-screen md:my-24 p-10	bg-white rounded-lg	shadow-2xl">
            {children}
            //</div></div>
      </body>
    </html>
  );
}
